version: '3.7'

services:
  wallet-notifications-service:
    build:
      context: .
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - .:/opt/app
      - /opt/app/node_modules
    command: npm run start:dev