export const WALLET_SERVICE_TOKEN = 'WALLET_SERVICE_TOKEN';
export const AIRDROP_TRANSACTION_REPOSITORY_TOKEN =
  'AIRDROP_TRANSACTION_REPOSITORY_TOKEN';

export const WALLET_EXCEPTIONS = {
  CHAIN_URL_NOT_CONFIGURED: 'evm_chain_url_not_configured',
  AIRDROP_SETTINGS_NOT_CONFIGURED: 'airdrop_settings_not_configured',
};
